import os

# Load environment variables from .env if python-dotenv is installed
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Base directory
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Upload and output folders (configurable via environment variables)
UPLOAD_FOLDER = os.environ.get("UPLOAD_FOLDER", os.path.join(BASE_DIR, "uploads"))
OUTPUT_FOLDER = os.environ.get("OUTPUT_FOLDER", os.path.join(BASE_DIR, "outputs"))
PASSPORT_OUTPUT_FOLDER = os.environ.get("PASSPORT_OUTPUT_FOLDER", os.path.join(OUTPUT_FOLDER, "passport"))
PRINTABLE_OUTPUT_FOLDER = os.environ.get("PRINTABLE_OUTPUT_FOLDER", os.path.join(OUTPUT_FOLDER, "printable"))

# Ensure directories exist
for folder in [UPLOAD_FOLDER, OUTPUT_FOLDER, PASSPORT_OUTPUT_FOLDER, PRINTABLE_OUTPUT_FOLDER]:
    os.makedirs(folder, exist_ok=True)

# Standard print DPI (Dots Per Inch) (configurable via environment variables)
DPI = int(os.environ.get("DPI", 300))

# Pre-fixed printable layout defaults
DEFAULT_MARGIN_MM = float(os.environ.get("DEFAULT_MARGIN_MM", 8.0))
DEFAULT_GAP_MM = float(os.environ.get("DEFAULT_GAP_MM", 2.5))

# rembg background removal model configuration
REMBG_MODEL = os.environ.get("REMBG_MODEL", "birefnet-general-lite")

# Conversion helper: mm to pixels at 300 DPI
def mm_to_px(mm, dpi=DPI):
    return int((mm / 25.4) * dpi)

# Conversion helper: inches to pixels
def inch_to_px(inches, dpi=DPI):
    return int(inches * dpi)

# ─────────────────────────────────────────────────────────────────────────────
# Country Rules Database
# ─────────────────────────────────────────────────────────────────────────────
# Schema per entry:
#   name                  – Display name
#   document_type         – Passport / Visa / ID
#   width_mm / height_mm  – Photo dimensions in mm
#   dpi                   – Print DPI
#   pixel_width/height    – Reference pixel dimensions at 300 DPI
#   head_height_min/max   – Head height range in mm (chin → crown)
#   head_height_ratio_*   – Head height as fraction of photo height
#   eye_height_ratio_*    – Eye-line as fraction of photo height from bottom
#   top_margin_mm         – Space above head (approx.)
#   bg_color / bg_color_hex – Required background
#   expression            – Facial expression requirement
#   mouth                 – Mouth requirement
#   eyes                  – Eyes requirement
#   glasses               – Glasses policy
#   head_cover            – Head-cover policy
#   shadows               – Shadow policy
#   smile                 – Smile policy
#   rotation_max_deg      – Maximum allowed head rotation
#   description           – Human-readable summary
# ─────────────────────────────────────────────────────────────────────────────
COUNTRY_RULES = {

    # ── Americas ──────────────────────────────────────────────────────────────
    "usa": {
        "name": "United States (USA)",
        "document_type": "Passport",
        "width_mm": 50.8,
        "height_mm": 50.8,
        "dpi": 300,
        "pixel_width": 600,
        "pixel_height": 600,
        "head_height_min": 25.0,
        "head_height_max": 35.0,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.69,
        "eye_height_ratio_min": 0.56,
        "eye_height_ratio_max": 0.69,
        "top_margin_mm": 5.0,
        "bg_color": "White / Off-White",
        "bg_color_hex": "#FFFFFF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral / Natural",
        "rotation_max_deg": 5,
        "description": "2×2 inches (51×51 mm). Head 25–35 mm. White or off-white background. Glasses not allowed since 2016."
    },

    "canada": {
        "name": "Canada",
        "document_type": "Passport",
        "width_mm": 50.0,
        "height_mm": 70.0,
        "dpi": 300,
        "pixel_width": 590,
        "pixel_height": 826,
        "head_height_min": 31.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.44,
        "head_height_ratio_max": 0.51,
        "eye_height_ratio_min": 0.52,
        "eye_height_ratio_max": 0.62,
        "top_margin_mm": 7.0,
        "bg_color": "White / Light-Colored",
        "bg_color_hex": "#FFFFFF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed (since 2021)",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "50×70 mm. Head height 31–36 mm. White or light-coloured background. Glasses banned since 2021."
    },

    # ── Europe ────────────────────────────────────────────────────────────────
    "uk": {
        "name": "United Kingdom (UK)",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 29.0,
        "head_height_max": 34.0,
        "head_height_ratio_min": 0.64,
        "head_height_ratio_max": 0.75,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Plain Cream / Light Grey",
        "bg_color_hex": "#F5F5F0",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Allowed (no tinted lenses, no glare)",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 29–34 mm. Plain cream or light grey background."
    },

    "germany": {
        "name": "Germany (Biometric)",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Gray",
        "bg_color_hex": "#E0E0E0",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. Light grey background. Biometric ICAO standard."
    },

    "france": {
        "name": "France",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Gray / Light Blue",
        "bg_color_hex": "#D3D3D3",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "No",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. Light gray or light blue background. White background is NOT accepted."
    },

    "italy": {
        "name": "Italy",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Gray / White",
        "bg_color_hex": "#EFEFEF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. Light grey or white background."
    },

    "spain": {
        "name": "Spain",
        "document_type": "Passport",
        "width_mm": 32.0,
        "height_mm": 26.0,
        "dpi": 300,
        "pixel_width": 378,
        "pixel_height": 307,
        "head_height_min": 18.0,
        "head_height_max": 22.0,
        "head_height_ratio_min": 0.65,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.50,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 2.0,
        "bg_color": "White",
        "bg_color_hex": "#FFFFFF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "32×26 mm (landscape format). White background."
    },

    "netherlands": {
        "name": "Netherlands",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Blue / White",
        "bg_color_hex": "#E8F4FD",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. Light blue or white background."
    },

    "belgium": {
        "name": "Belgium",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "White / Light Gray",
        "bg_color_hex": "#F5F5F5",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. White or light gray background."
    },

    "switzerland": {
        "name": "Switzerland",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Gray / White",
        "bg_color_hex": "#E8E8E8",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. Light gray or white background."
    },

    "austria": {
        "name": "Austria",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Gray / White",
        "bg_color_hex": "#EFEFEF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. Light gray or white background. ICAO biometric."
    },

    "norway": {
        "name": "Norway",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Gray / White",
        "bg_color_hex": "#EFEFEF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. Light gray or white background."
    },

    "sweden": {
        "name": "Sweden",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Gray / White",
        "bg_color_hex": "#EFEFEF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. Light gray or white background."
    },

    "denmark": {
        "name": "Denmark",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Gray / White",
        "bg_color_hex": "#EFEFEF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. Light gray or white background."
    },

    "finland": {
        "name": "Finland",
        "document_type": "Passport",
        "width_mm": 36.0,
        "height_mm": 47.0,
        "dpi": 300,
        "pixel_width": 425,
        "pixel_height": 555,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.68,
        "head_height_ratio_max": 0.77,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 5.0,
        "bg_color": "Light Gray / White",
        "bg_color_hex": "#F0F0F0",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "36×47 mm. Head 32–36 mm. Light gray or white background."
    },

    "poland": {
        "name": "Poland",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Gray / White",
        "bg_color_hex": "#F0F0F0",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. White or light gray background."
    },

    "portugal": {
        "name": "Portugal",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "White / Light Gray",
        "bg_color_hex": "#F5F5F5",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. White or light gray background."
    },

    "ireland": {
        "name": "Ireland",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 29.0,
        "head_height_max": 34.0,
        "head_height_ratio_min": 0.64,
        "head_height_ratio_max": 0.75,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "White / Light Gray",
        "bg_color_hex": "#F5F5F5",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 29–34 mm. White or light gray background."
    },

    # ── Asia-Pacific ──────────────────────────────────────────────────────────
    "india": {
        "name": "India",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.70,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "White",
        "bg_color_hex": "#FFFFFF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Allowed (eyes must be fully visible)",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm (70–80%). Plain white background."
    },

    "australia": {
        "name": "Australia",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Gray / White",
        "bg_color_hex": "#EAEAEA",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. Plain light gray or white background."
    },

    "new_zealand": {
        "name": "New Zealand",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Gray / White",
        "bg_color_hex": "#EAEAEA",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. Plain light gray or white background."
    },

    "japan": {
        "name": "Japan",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "Light Blue / White",
        "bg_color_hex": "#ADD8E6",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "No",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. Plain off-white or light blue background."
    },

    "south_korea": {
        "name": "South Korea",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "White",
        "bg_color_hex": "#FFFFFF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. White background."
    },

    "china": {
        "name": "China",
        "document_type": "Passport",
        "width_mm": 33.0,
        "height_mm": 48.0,
        "dpi": 300,
        "pixel_width": 390,
        "pixel_height": 567,
        "head_height_min": 28.0,
        "head_height_max": 33.0,
        "head_height_ratio_min": 0.58,
        "head_height_ratio_max": 0.69,
        "eye_height_ratio_min": 0.50,
        "eye_height_ratio_max": 0.62,
        "top_margin_mm": 5.0,
        "bg_color": "White / Light Blue",
        "bg_color_hex": "#F0F8FF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "33×48 mm. Head 28–33 mm. White or light blue background."
    },

    "singapore": {
        "name": "Singapore",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "White",
        "bg_color_hex": "#FFFFFF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. White background."
    },

    "malaysia": {
        "name": "Malaysia",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 50.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 591,
        "head_height_min": 33.0,
        "head_height_max": 40.0,
        "head_height_ratio_min": 0.66,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "White / Light Blue",
        "bg_color_hex": "#F0F8FF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Allowed (no tinted lenses)",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×50 mm. Head 33–40 mm. White or light blue background."
    },

    "indonesia": {
        "name": "Indonesia",
        "document_type": "Passport",
        "width_mm": 40.0,
        "height_mm": 60.0,
        "dpi": 300,
        "pixel_width": 472,
        "pixel_height": 709,
        "head_height_min": 35.0,
        "head_height_max": 48.0,
        "head_height_ratio_min": 0.58,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 5.0,
        "bg_color": "White / Light Blue",
        "bg_color_hex": "#F0F8FF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "40×60 mm. Head 35–48 mm. White or light blue background."
    },

    "thailand": {
        "name": "Thailand",
        "document_type": "Passport",
        "width_mm": 35.0,
        "height_mm": 45.0,
        "dpi": 300,
        "pixel_width": 413,
        "pixel_height": 531,
        "head_height_min": 32.0,
        "head_height_max": 36.0,
        "head_height_ratio_min": 0.71,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "White",
        "bg_color_hex": "#FFFFFF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Not Allowed (except religious)",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "35×45 mm. Head 32–36 mm. White background."
    },

    # ── Middle East ───────────────────────────────────────────────────────────
    "uae": {
        "name": "United Arab Emirates (UAE)",
        "document_type": "Passport",
        "width_mm": 40.0,
        "height_mm": 60.0,
        "dpi": 300,
        "pixel_width": 472,
        "pixel_height": 709,
        "head_height_min": 35.0,
        "head_height_max": 48.0,
        "head_height_ratio_min": 0.58,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 5.0,
        "bg_color": "White",
        "bg_color_hex": "#FFFFFF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Allowed for women",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "40×60 mm. Head 35–48 mm. White background. Head cover allowed for women."
    },

    "saudi_arabia": {
        "name": "Saudi Arabia",
        "document_type": "Passport",
        "width_mm": 40.0,
        "height_mm": 60.0,
        "dpi": 300,
        "pixel_width": 472,
        "pixel_height": 709,
        "head_height_min": 35.0,
        "head_height_max": 48.0,
        "head_height_ratio_min": 0.58,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 5.0,
        "bg_color": "White",
        "bg_color_hex": "#FFFFFF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Allowed for women",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "40×60 mm. Head 35–48 mm. White background. Head cover allowed for women."
    },

    "qatar": {
        "name": "Qatar",
        "document_type": "Passport",
        "width_mm": 38.0,
        "height_mm": 48.0,
        "dpi": 300,
        "pixel_width": 449,
        "pixel_height": 567,
        "head_height_min": 30.0,
        "head_height_max": 38.0,
        "head_height_ratio_min": 0.63,
        "head_height_ratio_max": 0.79,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "White",
        "bg_color_hex": "#FFFFFF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Allowed for women",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "38×48 mm. Head 30–38 mm. White background."
    },

    "kuwait": {
        "name": "Kuwait",
        "document_type": "Passport",
        "width_mm": 40.0,
        "height_mm": 50.0,
        "dpi": 300,
        "pixel_width": 472,
        "pixel_height": 591,
        "head_height_min": 33.0,
        "head_height_max": 40.0,
        "head_height_ratio_min": 0.66,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 4.0,
        "bg_color": "White",
        "bg_color_hex": "#FFFFFF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Allowed for women",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "40×50 mm. Head 33–40 mm. White background."
    },

    "oman": {
        "name": "Oman",
        "document_type": "Passport",
        "width_mm": 40.0,
        "height_mm": 60.0,
        "dpi": 300,
        "pixel_width": 472,
        "pixel_height": 709,
        "head_height_min": 35.0,
        "head_height_max": 48.0,
        "head_height_ratio_min": 0.58,
        "head_height_ratio_max": 0.80,
        "eye_height_ratio_min": 0.55,
        "eye_height_ratio_max": 0.65,
        "top_margin_mm": 5.0,
        "bg_color": "White",
        "bg_color_hex": "#FFFFFF",
        "expression": "Neutral",
        "mouth": "Closed",
        "eyes": "Open",
        "glasses": "Not Allowed",
        "head_cover": "Allowed for women",
        "shadows": "Not Allowed",
        "smile": "Neutral",
        "rotation_max_deg": 5,
        "description": "40×60 mm. Head 35–48 mm. White background."
    },
}


# Standard Paper Sizes
# Dimensions in millimeters (mm)
PAPER_SIZES = {
    "4x6": {
        "name": "4 x 6 inches (Photo Paper)",
        "width_mm": 102.0,
        "height_mm": 152.0,
        "default_margin_mm": 3.0,
        "default_gap_mm": 2.0
    },
    "5x7": {
        "name": "5 x 7 inches (Photo Paper)",
        "width_mm": 127.0,
        "height_mm": 178.0,
        "default_margin_mm": 4.0,
        "default_gap_mm": 2.0
    },
    "A4": {
        "name": "A4 Standard (Document)",
        "width_mm": 210.0,
        "height_mm": 297.0,
        "default_margin_mm": 5.0,
        "default_gap_mm": 2.0
    },
    "Letter": {
        "name": "Letter Standard",
        "width_mm": 215.9,
        "height_mm": 279.4,
        "default_margin_mm": 5.0,
        "default_gap_mm": 2.0
    },
    "Legal": {
        "name": "Legal Standard",
        "width_mm": 215.9,
        "height_mm": 355.6,
        "default_margin_mm": 5.0,
        "default_gap_mm": 2.0
    }
}
